### ISSUE TITLE
lm should have an option to (not) launch the web browser

### ISSUE THREAD

**Issue by alexandredubois** [RedRise/lm#13]
Hello,

I tried your program on my nas (a Netgear Readynas, debian powered) which seems to be exactly what i was looking for ! 

As an improvement, you could add a new parameter which will specify if the web browser should be launch (or not) after the html generation. This feature would allow to launch "lm" with a cron task for example.

**Comment by RedRise** [comment]
Good remark.

**Comment by RedRise** [comment]
Can you try the last version.
I added the option --html-build which build the sumup html document without displaying it.
