### ISSUE TITLE
Dependency instruction incomplete

### ISSUE THREAD

**Issue by rvrignaud** [RedRise/lm#2]
Hello, 
I tried to install lm with your instruction found here : http://redrises.blogspot.com/2012/02/lm-list-movies-command-line-tool-lm.html

In my Debian 6.0 (stable) I didn't had the lib python argparse and I had to install debian package "python-argparse" for lm to work properly. I think this should be added in documentation.

Anyway congratulation for your work.

Romain

**Comment by RedRise** [comment]
Thank you for this pertinent remark.
Precised in README.md
