### ISSUE TITLE
Error when using --confirm

### ISSUE THREAD

**Issue by rvrignaud** [RedRise/lm#3]
See below problem:

Do you confirm stored info? (y/n):n
Will you provide an IMDb id? (y/n):y
please enter the IMDb id for this movie:1637688
--> movie found title: In Time
--> movie found  year: 2011
Confirm this result? (y/n):y
Traceback (most recent call last):
  File "/usr/local/bin/lm", line 1314, in <module>
    LM.manual_confirm(files)
  File "/usr/local/bin/lm", line 807, in manual_confirm
    update_count += self.__manual_confirm( f )
  File "/usr/local/bin/lm", line 850, in __manual_confirm
    { 'g_title':title, 'g_year':year, 'g_unsure':False })
UnboundLocalError: local variable 'title' referenced before assignment

**Comment by RedRise** [comment]
This bug should be corrected in the last commit
